// SCardService.idl : IDL source for SCardService
//

// This file will be processed by the MIDL tool to
// produce the type library (SCardService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(238AEEC9-AD5D-4D75-8F32-F6E3CC8EB90E),
	version(1.0),
]
library SCardServiceLib
{
	importlib("stdole2.tlb");
};

